server:
  port: 9090
  
management:
    port: 9091
    address: 127.0.0.1
  
spring:
    application:
        exchange: payments.events.fanout.exchange
        queue: payments.default.queue
        databaseName: paymentsdb
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/paymentsdb
    datasource:
        url: jdbc:h2:~/paymentsdb
        username: sa
        password:

#        url: jdbc:h2:mem:exploredb
#        driverClassName: org.h2.Driver
#        username: sa
#        password:
#        validation-query: SELECT 1;
#        initial-size: 2
#        sql-script-encoding: UTF-8
#    jpa:
#        database: h2
#        show-sql: true
#        hibernate:
#            ddl-auto: create
      
logging:
    level:
        root: INFO
        org.springframework: INFO
        org.axonframework: INFO
        payments: INFO
    file: ./logs/payments-service.log
    
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
          