server:
  port: 9095
  
management:
    port: 9096
    address: 127.0.0.1
  
spring:
    application:
        exchange: payments.events.fanout.exchange
        queue: accounts.default.queue
        databaseName: accountsdb
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: localhost
        username: guest
        password: guest
      
logging:
    level:
        root: INFO
        org.springframework: INFO
        org.axonframework: INFO
        payments: INFO
    file: ./logs/accounting-service.log
